# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/neurofleet
spring.datasource.username=root
spring.datasource.password=Keerthi@123

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect